spring:
  application.name: file-uploader

  datasource:
    url: jdbc:postgresql://209.46.126.200:5432/fileupload_db
    username: nextech
    password: 44Dhu9$j5
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082

file:
  upload-dir: /var/www/uploads
  baseUrl: http://209.46.126.200:8082/uploads/


