spring:
  application.name: file-uploader

  datasource:
    url: jdbc:postgresql://209.46.124.224:5432/fileupload_fb
    username: nextech
    password: 9^tpg76M8
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

#file:
#  upload-dir: /var/www/uploads


