spring:
  application.name: file-uploader

  datasource:
    url: jdbc:postgresql://209.46.126.200:5432/fileupload_fb
    username: nextech
    password: 52Qc@cj31
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082

file:
  upload-dir: /var/www/uploads


